name: vegapunk_env
channels:
  - defaults
  - conda-forge
  - nvidia
  - pytorch
  - pyg
dependencies:
  - python=3.9.18
  - pip=23.3
  - cycler=0.11.0
  - matplotlib=3.8.0
  - numpy=1.23.3
  - pytest=7.1.2
  - scipy=1.10.0
  - sphinx_rtd_theme=1.2.0
  - tqdm=4.65.0
  - shapely=2.0.2
  # Check:
  # https://pytorch.org/get-started/locally/
  # https://pytorch.org/get-started/previous-versions/
  # https://anaconda.org/pytorch/pytorch
  # https://anaconda.org/pytorch/torchvision
  # https://anaconda.org/pytorch/torchaudio
  # https://anaconda.org/pytorch/pytorch-cuda
  - pytorch::pytorch=2.0.1
  - pytorch::torchvision=0.15.2
  - pytorch::torchaudio=2.0.2
  - pytorch::pytorch-cuda=11.8
  # Check:
  # https://pytorch-geometric.readthedocs.io/en/latest/install/installation.html
  # https://anaconda.org/pyg/pyg
  - pyg::pyg=2.4.0
  - pip:
    - scikit_learn==1.3.0
    - f3dasm==1.2.0