name: hookeai_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9.18
  - pip=23.3
  - cycler=0.11.0
  - matplotlib=3.8.0
  - numpy=1.23.3
  - pandas=2.1.1
  - pytest=7.1.2
  - coverage=7.3.2
  - scipy=1.10.0
  - sphinx_rtd_theme=1.2.0
  - tqdm=4.65.0
  - shapely=2.0.2
  - hydra-core=1.3.2
  - torchinfo=1.8.0
  - pip:
      - scikit_learn==1.3.0
      - hydra-nevergrad-sweeper==1.3.0.dev0
      - hydra-optuna-sweeper==1.2.0
      - sqlalchemy==1.4.44

  # ---------------------------------------------------------------------------
  # PyTorch installation (manual)
  # ---------------------------------------------------------------------------
  # PyTorch and related packages (torch, torchvision, torchaudio) must be
  # installed manually according to your system configuration. HookeAI supports
  # CPU and CUDA installations.
  #
  # Visit: https://pytorch.org/get-started/locally/
  #
  # ---------------------------------------------------------------------------
